### ISSUE TITLE
[NeoButton]Animate twice when `toggle mode` button tapped.

### ISSUE THREAD

**Issue by shuheydev** [felipebaltazar/Xamarin.Forms.NeoControls#1]
Thanks for your great work, your NeoControls are beautiful! I love this one.

Look into NeoButton control, When I set ClickMode property as `Toggle` and tapped it, I found the tapped animation looks like occurred twice.
 
![20200426_220804](https://user-images.githubusercontent.com/43431002/80308535-917a8e00-880a-11ea-9930-74a2904a4939.gif)

So I would like to propose like below.

```cs
         private static async Task PerformIsCheckedAnimationAsync(NeoButton neoButton)
         {
             await neoButton.AnimateClick(neoButton.ShadowDistance * -1);
             //await neoButton.AnimateClick(neoButton.ShadowDistance);
         }
```

Result :

![20200426_223833](https://user-images.githubusercontent.com/43431002/80309245-c688df80-880e-11ea-99bf-74009befb5d0.gif)

Please consider about this if you like.

Thank you.

**Comment by felipebaltazar** [comment]
Thanks for you feedback!
Yeah we need some improvements for animations and draw performance.
I will check it

**Comment by shuheydev** [comment]
Thanks!😀
