### ISSUE TITLE
Circular buttons

### ISSUE THREAD

**Issue by robfrancis** [felipebaltazar/Xamarin.Forms.NeoControls#11]
I have tried to create a circular button by having the corner radius equal to the height / 2. However this doesn't seem to work.

```
<neo:Button .....
    HeightRequest="80"
    WidthRequest="80"
    CornerRadius="40"
 />
```

Do you have any idea why this is.

**Comment by felipebaltazar** [comment]
Hello @robfrancis!
Can you share a PrintScreen of the result you are getting?

**Comment by robfrancis** [comment]
![Android_Emulator_-_Pixel_3_XL_API_29_5554](https://user-images.githubusercontent.com/5869183/104518882-91e2df80-564c-11eb-95d9-d2834b1fce7b.png)

![iSystainApp_–_BottomTabPanelView_xaml](https://user-images.githubusercontent.com/5869183/104518972-c060ba80-564c-11eb-8dde-81dc2e709bf4.png)
