### ISSUE TITLE
ChangeCanExecute via the Xamarin Form Command Interface

### ISSUE THREAD

**Issue by R00iBaard** [felipebaltazar/Xamarin.Forms.NeoControls#14]
Hi there,

Firstly thanks so much for the library! Its really great!

However, converting from Syncfusion buttons to this, I am having issues with ChangeCanExecute... triggering this no longer calls the Func<object, bool> canExecute for the specific Command. I am using this to enable/disable the button as well as change the background colors.

**Comment by felipebaltazar** [comment]
hey man!
Thanks for the feedback, i will check this issue soon as possible..
Feel free to send PR if you find the fix

**Comment by bricefriha** [comment]
Hi folks,

I could help if you need to! 😉
What are the steps to reproduce the issues?

**Comment by felipebaltazar** [comment]
I'm closing the issue, given the time without interaction.
Feel free to reopen it if you are still having problems.

Thanks!
