### ISSUE TITLE
MAUI port

### ISSUE THREAD

**Issue by bricefriha** [felipebaltazar/Xamarin.Forms.NeoControls#15]
Hey there!

Great job with this package, I wanted to know, are you planning on creating a .NET MAUI port of this package. it would be neat, wouldn't it? 😁

If you need some help to do it I might be able to give you some 😉

**Comment by felipebaltazar** [comment]
Hey @bricefriha!
Yeah I definitely will port it to Maui
Your help is welcome!

**Comment by felipebaltazar** [comment]
Hello @bricefriha !
I've created a Maui repository for this package:
https://github.com/felipebaltazar/Maui.NeoControls

It is still on pre-release because we need to test more, contributions are welcome!
For now I will close this issue.

Thanks

**Comment by mediaexplorer74** [comment]
Cool. Maybe, one day you add UWP to [Xamarin.Forms.NeoControls](https://github.com/felipebaltazar/Xamarin.Forms.NeoControls) ;)

Cheers up,
M.E.
